name: CI_dev
on:
    push:
        branches:
            - dev
    workflow_dispatch:
jobs:
    migrate:
        runs-on: ubuntu-latest
        environment: dev
        container:
            image: flyway/flyway
        steps:
            - uses: actions/checkout@v3
            - name: Run flyway migrate
              run:
                -- webegt
                -- set flyway_path
                set JAVA_ARGS=--add-opens=java.base/java.nio=ALL-UNNAMED
                flyway -user=${{secrets.SNOWFLAKE_USER}} -password=${{secrets.SNOWFLAKE_PASSWORD}} -configFiles=configs/dev.conf migrate
              shell: bash